import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AppProvider from '@src/providers'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js Template by Duckiee',
  description: 'Generated by create next app',
  icons: ['/favicon.png'],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
